[package]
name = "Jit_compiler"
version = "0.1.0"
authors = ["pierre"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.62"
mac_address = "1.0.2"